export const LANG = {
  id: {
    dashboard:"Beranda", transactions:"Transaksi", report:"Laporan", date:"Date", settings:"Pengaturan",
    monthlyExpense:"Pengeluaran bulan ini", today:"Hari ini", remaining:"Sisa", budgetLeft:"tersisa",
    morning:"Selamat pagi", afternoon:"Selamat siang", evening:"Selamat sore", night:"Selamat malam",
    savingsGoal:"Target Tabungan", recentTx:"Transaksi Terbaru", seeAll:"Lihat Semua",
    breakdown:"Breakdown Kategori", weeklyTrend:"Tren Mingguan", monthlyBudget:"Budget Bulanan",
    addTx:"Tambah Transaksi", editTx:"Edit Transaksi", newTx:"Transaksi Baru", save:"Simpan", cancel:"Batal", delete:"Hapus",
    amount:"Jumlah", description:"Keterangan", category:"Kategori", location:"Lokasi", note:"Catatan",
    date_label:"Tanggal", addGoal:"Tambah Target", editGoal:"Edit Target",
    amountPlaceholder:"Jumlah (Rp)", descPlaceholder:"Keterangan...", locPlaceholder:"Lokasi (opsional)", notePlaceholder:"Catatan (opsional)",
    settingsTitle:"Pengaturan", profile:"Profil", profileName:"Nama profil",
    appearance:"TAMPILAN", displayMode:"Mode Tampilan", darkActive:"Mode gelap aktif", lightActive:"Mode terang aktif",
    followSystem:"Ikuti Sistem", followSystemDesc:"Otomatis dari pengaturan HP", manualMode:"Mode diatur manual",
    colorTheme:"Tema Warna", colorCustom:"Warna Custom", language:"Bahasa", languageDesc:"Pilih bahasa tampilan",
    notifications:"NOTIFIKASI", notifActive:"Aktif — setiap hari jam 9 malam", notifOff:"Nonaktif",
    data:"DATA", exportData:"Ekspor Data", exportCSV:"Ekspor CSV",
    exportReport:"Ekspor Laporan", dangerZone:"ZONA BAHAYA", resetData:"Atur Ulang Semua Data",
    resetConfirm:"Yakin ingin menghapus semua data? Tidak bisa dibatalkan.",
    income:"Pemasukan", editIncome:"Edit Pemasukan", monthlyIncome:"Pemasukan Bulanan (Rp)", incomePlaceholder:"Contoh: 5000000",
    txAdded:"Transaksi ditambahkan", txUpdated:"Transaksi diperbarui", txDeleted:"Transaksi dihapus", txUndo:"Batal",
    nameSaved:"Nama disimpan", incomeSaved:"Pemasukan diperbarui",
    safe:"Aman", warning:"Perhatian", critical:"Kritis",
    budgetSafe:"Budget aman", budgetWarn:"Perhatikan budget", budgetCrit:"Hampir habis",
    addTarget:"Tambah Target", editTarget:"Edit Target", goalName:"Nama Target", goalTarget:"Target (Rp)", goalSaved:"Sudah Ditabung (Rp)",
    goalColor:"Warna", saveTarget:"Simpan Target", goalReached:"Target tercapai!",
    goalOverdue:"Sudah lewat", goalDaysLeft:"hari lagi",
    goalNamePlaceholder:"Contoh: Ganti HP", goalAmtPlaceholder:"Contoh: 5000000", goalSavedPlaceholder:"Contoh: 1500000",
    noTx:"Belum ada transaksi", noGoal:"Belum ada target tabungan", addFirst:"Yuk, buat target pertamamu!",
    noTxDesc:"Mulai catat pengeluaran hari ini", noTxDescEmpty:"Yuk, mulai catat pengeluaran pertamamu hari ini!",
    noTxFound:"Tidak ditemukan", noTxFoundDesc:"Tidak ada hasil untuk",
    startDesc:"Mulai catat pengeluaran untuk melihat laporan dan insight keuanganmu.",
    thisWeek:"Minggu Ini", avgPerDay:"Rata-rata/hari", transactions_label:"transaksi",
    add:"Tambah", edit:"Edit", from:"dari", days:"hari berjalan", done:"Selesai", use:"Gunakan", active:"Aktif",
    tapName:"Tap untuk isi nama", namePlaceholder:"Nama kamu...", search:"Cari transaksi...",
    filterToday:"Hari ini", filterWeek:"Minggu ini", filterMonth:"Bulan ini",
    thisMonth:"Bulan ini", lastMonth:"Bulan lalu",
    budgetLimit:"Batas Pengeluaran", budgetLimitDesc:"Atur batas pengeluaran per kategori",
    manageCategory:"Kelola Kategori", addCategory:"Tambah Kategori", editCategory:"Edit Kategori",
    catName:"Nama kategori...", pickIcon:"Pilih Ikon:", pickColor:"Pilih Warna:",
    previewLabel:"Preview", activeCategories:"Kategori Aktif",
    pickDate:"Pilih Tanggal", avgPerTx:"Rata-rata per transaksi:", noTxDate:"Tidak ada transaksi pada tanggal ini",
    setLimit:"Batas",
    addWishlist:"Tambah Wishlist Date", wishlistPlaceholder:"Contoh: Dinner di rooftop...",
    recordDate:"Catat Pengeluaran Date", noDateTx:"Belum ada pengeluaran date",
    noRecurring:"Belum ada transaksi rutin", recurAmtPlaceholder:"Jumlah (Rp)",
    recurNamePlaceholder:"Nama (mis: Kos, Netflix...)",
    themePreset:"PRESET TEMA", themeGreen:"Hijau", themeBlue:"Biru", themePurple:"Ungu", themeRose:"Merah", themeOrange:"Oranye", themeTeal:"Teal",
    orCustom:"atau custom", primaryLabel:"UTAMA", accentLabel:"AKSEN",
    primaryFull:"WARNA UTAMA", accentFull:"WARNA AKSEN",
    dailyReminder:"Pengingat Harian",
    dateBudgetTitle:"BUDGET DATE BULAN INI", dateActivities:"aktivitas date",
    wishlistTitle:"Wishlist Date", noWishlist:"Belum ada wishlist date",
    wishlistSub:"Tambahkan tempat impian kalian",
    dateRecord:"Catat Pengeluaran Date", noDateExp:"Belum ada pengeluaran date",
    addDateBtn:"+ Catat",
    targetDate:"Target Tanggal (opsional)",
    noData:"Belum ada data bulan ini", startNote:"Mulai catat pengeluaran hari ini",
    toastGoalSaved:"ok:Target tabungan disimpan", toastRecurAdd:"ok:Transaksi rutin ditambahkan",
    toastRecurEdit:"ok:Rutin diperbarui", toastRecurDel:"del:Rutin dihapus",
    toastWishlist:"ok:Ditambahkan ke wishlist", toastReportOk:"ok:Laporan berhasil dibuat",
    toastAddHome:"info:Tambahkan ke Home Screen dulu",
    toastReminderOn:"ok:Pengingat harian aktif jam 9 malam", toastReminderOff:"info:Pengingat dinonaktifkan",
    shareSummary:"Bagikan Ringkasan", shareCopied:"ok:Ringkasan disalin!", shareWhatsapp:"Bagikan ke WhatsApp", shareCopy:"Salin Teks",
    shareTitle:"Laporan Keuangan", swipeHint:"← Geser untuk hapus",
    addExpense:"+ Tambah Pengeluaran", addRecurring:"Tambah Rutin", recurringTx:"TRANSAKSI RUTIN",
    recurDay:"Tgl", recurEach:"tiap bulan", recurDeleted:"Rutin dihapus", recurEdited:"Rutin diperbarui", dayLabel:"Tgl (1-31):",
    autoApply:"Terapkan Otomatis", autoApplyDesc:"Catat otomatis tiap bulan saat tanggal tiba",
    allCategories:"Semua Kategori", breakdownCat:"Rincian Kategori", trend8w:"Tren 8 Minggu",
    sortNewest:"Terbaru", sortOldest:"Terlama", sortHighest:"Terbesar", sortLowest:"Terkecil",
    totalExpense:"TOTAL PENGELUARAN", totalToday:"TOTAL HARI INI", perCategory:"Per Kategori",
    txDetail:"Detail Transaksi", insightToday:"Insight Hari Ini", topSpend:"Terbanyak:",
    aboveAvg:"Melebihi rata-rata harian", belowAvg:"Di bawah rata-rata harian",
    budgetMonthly:"BUDGET BULANAN", notEnoughData:"Belum cukup data",
    notEnoughDataDesc:"Grafik perbandingan antar bulan akan muncul setelah ada data dari 2 bulan berbeda.",
    goalRemaining:"Sisa", goalRemainingMore:"lagi",
    insightMore:"lebih banyak", insightLess:"lebih hemat", insightFrom:"dari bulan lalu",
    insightUp:"naik", insightDown:"turun",
    previewHeader:"Preview Header",
    deleteTxTitle:"Hapus Transaksi?", deleteTxDesc:"Transaksi ini akan dihapus permanen.",
    repInsightMonthly:"Insight Bulanan", repInsightWeekly:"Insight Mingguan",
    repWeekTotal:"Total minggu ini:", repMoreSpend:"Lebih boros", repLessSpend:"Lebih hemat",
    repVsLastWeek:"vs minggu lalu", repTopCat:"Kategori terbanyak:",
    showMore:"Lihat Lebih", backupData:"Cadangkan Data", backupDesc:"Unduh semua data sebagai JSON", restoreBackup:"Pulihkan Cadangan", restoreDesc:"Impor dari file cadangan", resetDesc:"Hapus semua data permanen", dataSubtitle:"Cadangkan, pulihkan & atur ulang", restoreConfirmMsg:"Pulihkan cadangan ini? Data saat ini akan diganti.",
    backupOk:"Cadangan berhasil diunduh", receiptPhoto:"Foto struk", receiptAdded:"ok:Foto struk ditambahkan", restoreOk:"Cadangan berhasil dipulihkan!",
    restoreConfirm:"Pulihkan cadangan ini? Data saat ini akan diganti.",
    backupInvalid:"File cadangan tidak valid",

    save:"Simpan", cancel:"Batal", done:"Selesai",
    notifications:"Notifikasi",

    cicilan:"Cicilan", addCicilan:"+ Tambah Cicilan", editCicilan:"Edit Cicilan",
    noCicilan:"Belum ada cicilan",
    cicilanDesc:"Cicilan otomatis dikurangi dari pemasukan tiap bulan",
    cicilanName:"Nama cicilan", cicilanMonthly:"Cicilan/bulan",
    cicilanDue:"Tanggal jatuh tempo", cicilanTotal:"Total harga",
    cicilanDuration:"Durasi (bulan)", cicilanProgress:"Progress cicilan",
    cicilanRemain:"bulan lagi", cicilanPaid:"Lunas",
    cicilanAlreadyPaid:"Sudah dibayar bulan ini",
    cicilanMarkPaid:"Tandai Lunas Bulan Ini",
    cicilanPaidToast:"ok:Cicilan bulan ini ditandai lunas",
    cicilanSaved:"ok:Cicilan disimpan", cicilanDeleted:"del:Cicilan dihapus",
    cicilanTotal2:"Total Cicilan/Bulan",

    reminderTitle:"Pengingat Transaksi",
    reminderDesc:"Notif kalau belum input pengeluaran hari ini",
    reminderTime:"Waktu Pengingat", reminderDays:"Hari Aktif",
    reminderSmart:"Pengingat Cerdas",
    reminderSmartDesc:"Lewati kalau sudah ada transaksi hari ini",
    reminderPreview:"Pratinjau Notifikasi",
    reminderOn:"ok:Pengingat aktif", reminderOff:"Pengingat dinonaktifkan",
    reminderNotifTitle:"🐾 Belum catat pengeluaran hari ini!",
    reminderNotifBody:"Jangan lupa input transaksi biar keuanganmu tetap terkontrol 🐱",

    // Split bills / Patungan
    splitBills:"Patungan", splitBillsDesc:"Bagi tagihan bareng teman dengan mudah",
    splitNew:"Split Bill Baru", splitEdit:"Edit Split Bill", splitSaved:"ok:Split bill disimpan",
    splitDeleted:"ok:Dihapus", splitActive:"AKTIF", splitSettled:"LUNAS",
    splitTitle:"Judul (mis. Makan di X)", splitTotal:"Total tagihan (mis. 300.000)",
    splitMembers:"Anggota (pisah koma)", splitPayer:"Siapa yang bayar duluan?",
    splitPayerPlaceholder:"Nama yang bayar", splitPerPerson:"/ orang",
    splitPeople:"orang", splitPaidBy:"Dibayar oleh", splitTapMark:"tap untuk tandai yang sudah bayar balik",
    splitPaidBill:"Yang bayar duluan 💳", splitHasPaid:"Sudah bayar balik ✓", splitNotPaid:"Belum bayar balik",
    splitAllSettled:"Semua lunas", splitBack:"← Kembali", splitEmpty:"Belum ada split bill",
    splitMinMembers:"Min 2 orang", splitPaidBack:"sudah bayar balik",
    splitPerson:"orang", splitOrg:"org", splitPerMonth:"per bulan", splitMonths:"bulan",

    // Recurring income
    recurringIncome:"PEMASUKAN RUTIN", addRecurringIncome:"Tambah Pemasukan Rutin",
    addIncome:"Tambah Pemasukan", recurIncomeAdded:"ok:Pemasukan rutin ditambahkan",
    saveAndAdd:"Simpan & Tambah", saveAndSubtract:"Simpan & Kurangi",

    // Offline indicator
    offlineTitle:"Kamu sedang offline", offlineDesc:"Tidak ada koneksi internet. Data tetap tersimpan di perangkat.",

    // Discard confirmation
    discardTitle:"Buang perubahan?", discardDesc:"Data yang sudah diisi akan hilang.",
    discardConfirm:"Buang", discardCancel:"Lanjut Edit",

    // Financial health
    financialHealth:"KESEHATAN FINANSIAL", healthExcellent:"Sangat Baik",
    healthGood:"Baik", healthFair:"Cukup", healthNeedAttention:"Perlu Perhatian",

    // Misc missing
    back:"← Kembali", recordNow:"Catat Sekarang", addSavings:"Tambah tabungan",
    addFirstTx:"Catat transaksi pertama", amountAdd:"Jumlah yang ditambah",
    amountSubtract:"Jumlah yang dikurangi", currentIncome:"Pemasukan saat ini",
    saveLimitBtn:"Simpan Batas", saveSettings:"Simpan Pengaturan", settingsSaved:"ok:Pengaturan disimpan",
    budgetRemoved:"Anggaran dihapus", budgetSavedMsg:"ok:Anggaran disimpan!",
    setBudget:"Atur Anggaran", totalMonthly:"Total Bulanan",
    totalSpendingCap:"Batas total pengeluaran per bulan",
    catTrend4m:"Tren Kategori (4 bulan)", weekSummary:"Ringkasan Mingguan",
    monthPrediction:"PREDIKSI AKHIR BULAN", thisWeekLabel:"MINGGU INI",
    topCategories:"KATEGORI TERBESAR", totalSpendingLabel:"TOTAL PENGELUARAN",
    tapOutsideClose:"Tap di luar untuk tutup", imageDownloaded:"ok:Gambar berhasil diunduh!",
    exportAsImage:"Ekspor sebagai Gambar", downloadImage:"Unduh Gambar",
    csvDownloaded:"ok:CSV berhasil didownload", incomeDeleted:"Pemasukan dihapus",
    incomeRecorded:"Pemasukan dicatat", incomeUpdated:"Pemasukan diperbarui",
    dailyNote:"Catatan Harian", dailyNotePlaceholder:"Bagaimana pengeluaranmu hari ini? Catatan tentang keuanganmu...",
    streakLabel:"STREAK", keepGoing:"Teruskan!", exceeded:"Terlampaui",
    nearLimit:"Mendekati batas", setNewLimit:"ATUR BATAS BARU (Rp)", currentLimit:"LIMIT SAAT INI",
    remaining:"Sisa", estSpending:"Est. pengeluaran: ", mostSpend:"Terbanyak: ",
    spentLabel:"terpakai", usedLabel:"terpakai", remainingLabel:"sisa",
    autoLabel:"· Otomatis", instLabel:"Cicilan ke-", dueLabel:"jatuh tempo",
    perMonthLabel:"per bulan", monthsLabel:"bulan", progressCicilan:"Progress cicilan",
    vsLastWeek:"vs minggu lalu", onFire:"Konsisten!", startTracking:"Yuk mulai catat pengeluaran hari ini.",
    changeAnytime:"Bisa diubah kapan saja di Pengaturan.", pushNotifications:"Notifikasi",
    cameraLabel:"Kamera", uploadLabel:"Unggah", removeLabel:"Hapus",
    editLabel:"Edit", recordLabel:"Catat", barLabel:"Bar", lineLabel:"Line",
    paidProgress:"Progress", cancelLabel:"Batal", saveLabel:"Simpan",
    thisMonthLabel:"Bulan ini", lastMonthLabel:"Bulan lalu",

  },

  en: {
    // Nav
    dashboard:"Home", transactions:"Transactions", report:"Reports", date:"Date", settings:"Settings",
    // Dashboard card
    monthlyExpense:"Monthly spending", today:"Today", remaining:"Left", budgetLeft:"remaining",
    // Header greetings
    morning:"Good morning", afternoon:"Good afternoon", evening:"Good evening", night:"Good evening",
    // Sections
    savingsGoal:"Savings Goals", recentTx:"Recent Transactions", seeAll:"See All",
    breakdown:"Category Breakdown", weeklyTrend:"Weekly Trend", monthlyBudget:"Monthly Budget",
    // Forms
    addTx:"Add Transaction", editTx:"Edit Transaction", newTx:"New Transaction", save:"Save", cancel:"Cancel", delete:"Delete",
    amount:"Amount", description:"Description", category:"Category", location:"Location", note:"Note",
    date_label:"Date", addGoal:"Add Goal", editGoal:"Edit Target",
    amountPlaceholder:"Amount (Rp)", descPlaceholder:"Description...", locPlaceholder:"Location (optional)", notePlaceholder:"Note (optional)",
    // Settings
    settingsTitle:"Settings", profile:"Profile", profileName:"Profile name",
    appearance:"APPEARANCE", displayMode:"Display Mode", darkActive:"Dark mode active", lightActive:"Light mode active",
    followSystem:"Follow System", followSystemDesc:"Automatic from device settings", manualMode:"Mode set manually",
    colorTheme:"Colour Theme", colorCustom:"Custom Colour", language:"Language", languageDesc:"Choose display language",
    notifications:"NOTIFICATIONS", notifActive:"Active — every day at 9 PM", notifOff:"Inactive",
    data:"DATA", exportData:"Export Data", exportCSV:"Export CSV",
    exportReport:"Export Report", dangerZone:"DANGER ZONE", resetData:"Reset All Data",
    resetConfirm:"Are you sure you want to delete all data? This cannot be undone.",
    // Income
    income:"Income", editIncome:"Edit Income", monthlyIncome:"Monthly Income (Rp)",
    incomePlaceholder:"e.g. 5000000",
    // Toast
    txAdded:"Transaction added", txUpdated:"Transaction updated", txDeleted:"Transaction deleted", txUndo:"Undo",
    nameSaved:"Name saved", incomeSaved:"Income updated",
    // Budget status
    safe:"Safe", warning:"Warning", critical:"Critical",
    budgetSafe:"Budget on track", budgetWarn:"Watch your budget", budgetCrit:"Nearly exhausted",
    // Goals
    addTarget:"Add Goal", editTarget:"Edit Goal", goalName:"Goal Name", goalTarget:"Target (Rp)", goalSaved:"Amount Saved (Rp)",
    goalColor:"Colour", saveTarget:"Save Goal", goalReached:"Goal reached!",
    goalOverdue:"Overdue", goalDaysLeft:"days left",
    goalNamePlaceholder:"e.g. New Phone", goalAmtPlaceholder:"e.g. 5000000", goalSavedPlaceholder:"e.g. 1500000",
    // Misc
    noTx:"No transactions yet", noGoal:"No savings goals yet", addFirst:"Create your first goal!",
    noTxDesc:"Start recording your spending today", noTxDescEmpty:"Start recording your first transaction today!",
    noTxFound:"Not found", noTxFoundDesc:"No results for",
    startDesc:"Start recording expenses to see your reports and financial insights.",
    thisWeek:"This Week", avgPerDay:"Avg/day", transactions_label:"transactions",
    add:"Add", edit:"Edit", from:"of", days:"days elapsed", done:"Done", use:"Use", active:"Active",
    tapName:"Tap to set name", namePlaceholder:"Your name...", search:"Search transactions...",
    filterToday:"Today", filterWeek:"This week", filterMonth:"This month",
    thisMonth:"This month", lastMonth:"Last month",
    // Category manager
    budgetLimit:"Spending Limits", budgetLimitDesc:"Set spending limits per category",
    manageCategory:"Manage Categories", addCategory:"Add Category", editCategory:"Edit Category",
    catName:"Category name...", pickIcon:"Choose Icon:", pickColor:"Choose Colour:",
    previewLabel:"Preview", activeCategories:"Active Categories",
    // Report
    pickDate:"Pick Date", avgPerTx:"Average per transaction:", noTxDate:"No transactions on this date",
    setLimit:"Limit",
    // Date tab
    addWishlist:"Add Date Wishlist", wishlistPlaceholder:"e.g. Rooftop dinner...",
    recordDate:"Record Date Expense", noDateTx:"No date expenses yet",
    // Recurring
    noRecurring:"No recurring transactions yet", recurAmtPlaceholder:"Amount (Rp)",
    recurNamePlaceholder:"Name (e.g. Rent, Netflix...)",
    // Preview
    themePreset:"COLOUR PRESETS", themeGreen:"Green", themeBlue:"Blue", themePurple:"Purple", themeRose:"Rose", themeOrange:"Orange", themeTeal:"Teal",
    orCustom:"or custom", primaryLabel:"PRIMARY", accentLabel:"ACCENT",
    primaryFull:"PRIMARY COLOUR", accentFull:"ACCENT COLOUR",
    dailyReminder:"Daily Reminder",
    dateBudgetTitle:"THIS MONTH'S DATE BUDGET", dateActivities:"date activities",
    wishlistTitle:"Date Wishlist", noWishlist:"No date wishlist yet",
    wishlistSub:"Add your dream date spots",
    dateRecord:"Record Date Expense", noDateExp:"No date expenses yet",
    addDateBtn:"+ Record",
    targetDate:"Target Date (optional)",
    noData:"No data for this month", startNote:"Start recording expenses today",
    toastGoalSaved:"ok:Savings goal saved", toastRecurAdd:"ok:Recurring transaction added",
    toastRecurEdit:"ok:Recurring updated", toastRecurDel:"del:Recurring deleted",
    toastWishlist:"ok:Added to wishlist", toastReportOk:"ok:Report created",
    toastAddHome:"info:Add to Home Screen first",
    toastReminderOn:"ok:Daily reminder set for 9 PM", toastReminderOff:"info:Reminder disabled",
    shareSummary:"Share Summary", shareCopied:"ok:Summary copied!", shareWhatsapp:"Share to WhatsApp", shareCopy:"Copy Text",
    shareTitle:"Finance Report", swipeHint:"← Swipe to delete",
    addExpense:"+ Add Expense", addRecurring:"Add Recurring", recurringTx:"RECURRING",
    recurDay:"Day", recurEach:"every month", recurDeleted:"Recurring deleted", recurEdited:"Recurring updated", dayLabel:"Day (1-31):",
    autoApply:"Auto-apply", autoApplyDesc:"Recorded automatically each month on due date",
    allCategories:"All Categories", breakdownCat:"Category Breakdown", trend8w:"8-Week Trend",
    sortNewest:"Newest", sortOldest:"Oldest", sortHighest:"Highest", sortLowest:"Lowest",
    totalExpense:"TOTAL SPENDING", totalToday:"TODAY\'S TOTAL", perCategory:"By Category",
    txDetail:"Transactions", insightToday:"Today\'s Insight", topSpend:"Top:",
    aboveAvg:"Above daily average", belowAvg:"Below daily average",
    budgetMonthly:"MONTHLY BUDGET", notEnoughData:"Not enough data",
    notEnoughDataDesc:"The monthly comparison chart will appear once you have data from 2 different months.",
    goalRemaining:"Need", goalRemainingMore:"more", showMore:"Show More",
    insightMore:"more than", insightLess:"less than", insightFrom:"last month",
    insightUp:"up", insightDown:"down",
    previewHeader:"Preview Header",
    deleteTxTitle:"Delete Transaction?", deleteTxDesc:"This transaction will be permanently deleted.",
    backupOk:"Backup downloaded", receiptPhoto:"Receipt", receiptAdded:"ok:Receipt added", restoreOk:"Backup restored!",
    restoreConfirm:"Restore this backup? Current data will be replaced.",
    backupInvalid:"Invalid backup file",
    backupData:"Backup Data", backupDesc:"Download all data as JSON", restoreBackup:"Restore Backup", restoreDesc:"Import from backup file", resetDesc:"Delete all data permanently", dataSubtitle:"Backup, restore & reset", restoreConfirmMsg:"Restore this backup? Current data will be replaced.",

    save:"Save", cancel:"Cancel", done:"Done",
    notifications:"Notifications",

    cicilan:"Instalments", addCicilan:"+ Add Instalment", editCicilan:"Edit Instalment",
    noCicilan:"No instalments yet",
    cicilanDesc:"Instalments are auto-deducted from monthly income",
    cicilanName:"Instalment name", cicilanMonthly:"Monthly payment",
    cicilanDue:"Due date", cicilanTotal:"Total price",
    cicilanDuration:"Duration (months)", cicilanProgress:"Progress",
    cicilanRemain:"months left", cicilanPaid:"Paid",
    cicilanAlreadyPaid:"Already paid this month",
    cicilanMarkPaid:"Mark Paid This Month",
    cicilanPaidToast:"ok:Instalment marked as paid",
    cicilanSaved:"ok:Instalment saved", cicilanDeleted:"del:Instalment deleted",
    cicilanTotal2:"Total Instalments/Month",

    reminderTitle:"Transaction Reminder",
    reminderDesc:"Notify if no spending recorded today",
    reminderTime:"Reminder Time", reminderDays:"Active Days",
    reminderSmart:"Smart Reminder",
    reminderSmartDesc:"Skip if transaction already recorded today",
    reminderPreview:"Notification Preview",
    reminderOn:"ok:Reminder activated", reminderOff:"Reminder deactivated",
    reminderNotifTitle:"🐾 No spending recorded today!",
    reminderNotifBody:"Don't forget to log transactions to stay on track 🐱",

    // Split bills
    splitBills:"Split Bills", splitBillsDesc:"Split bills with friends easily",
    splitNew:"New Split Bill", splitEdit:"Edit Split", splitSaved:"ok:Split bill saved",
    splitDeleted:"ok:Deleted", splitActive:"ACTIVE", splitSettled:"SETTLED",
    splitTitle:"Title (e.g. Dinner at X)", splitTotal:"Total bill (e.g. 300.000)",
    splitMembers:"Members (comma-separated)", splitPayer:"Who paid?",
    splitPayerPlaceholder:"Name of payer", splitPerPerson:"/ person",
    splitPeople:"people", splitPaidBy:"Paid by", splitTapMark:"tap to mark who has paid back",
    splitPaidBill:"Paid the bill 💳", splitHasPaid:"Has paid back ✓", splitNotPaid:"Hasn't paid back",
    splitAllSettled:"All settled", splitBack:"← Back", splitEmpty:"No split bills yet",
    splitMinMembers:"Min 2 members", splitPaidBack:"paid back",
    splitPerson:"person", splitOrg:"person", splitPerMonth:"per month", splitMonths:"months",

    // Recurring income
    recurringIncome:"RECURRING INCOME", addRecurringIncome:"Add Recurring Income",
    addIncome:"Add Income", recurIncomeAdded:"ok:Recurring income added",
    saveAndAdd:"Save & Add", saveAndSubtract:"Save & Subtract",

    // Offline indicator
    offlineTitle:"You're offline", offlineDesc:"No internet connection. Your data is safely stored on this device.",

    // Discard confirmation
    discardTitle:"Discard changes?", discardDesc:"Any data you've entered will be lost.",
    discardConfirm:"Discard", discardCancel:"Keep Editing",

    // Financial health
    financialHealth:"FINANCIAL HEALTH", healthExcellent:"Excellent",
    healthGood:"Good", healthFair:"Fair", healthNeedAttention:"Need Attention",

    // Misc missing
    back:"← Back", recordNow:"Record Now", addSavings:"Add savings",
    addFirstTx:"Add first transaction", amountAdd:"Amount to add",
    amountSubtract:"Amount to subtract", currentIncome:"Current income",
    saveLimitBtn:"Save Limit", saveSettings:"Save Settings", settingsSaved:"ok:Settings saved",
    budgetRemoved:"Budget removed", budgetSavedMsg:"ok:Budget saved!",
    setBudget:"Set Budget", totalMonthly:"Total Monthly",
    totalSpendingCap:"Total spending cap per month",
    catTrend4m:"Category Trend (4 months)", weekSummary:"Weekly Summary",
    monthPrediction:"MONTH PREDICTION", thisWeekLabel:"THIS WEEK",
    topCategories:"TOP CATEGORIES", totalSpendingLabel:"TOTAL SPENDING",
    tapOutsideClose:"Tap outside to close", imageDownloaded:"ok:Image downloaded!",
    exportAsImage:"Export as Image", downloadImage:"Download Image",
    csvDownloaded:"ok:CSV downloaded successfully", incomeDeleted:"Income deleted",
    incomeRecorded:"Income recorded", incomeUpdated:"Income updated",
    dailyNote:"Daily Note", dailyNotePlaceholder:"How was your spending today? Any notes about your finances...",
    streakLabel:"STREAK", keepGoing:"Keep going!", exceeded:"Exceeded",
    nearLimit:"Near limit", setNewLimit:"SET NEW LIMIT (Rp)", currentLimit:"CURRENT LIMIT",
    remaining:"Remaining", estSpending:"Est. spending: ", mostSpend:"Most: ",
    spentLabel:"spent", usedLabel:"used", remainingLabel:"remaining",
    autoLabel:"· Auto", instLabel:"Inst.", dueLabel:"due",
    perMonthLabel:"per month", monthsLabel:"months", progressCicilan:"Progress",
    vsLastWeek:"vs last week", onFire:"On fire!", startTracking:"Start tracking your spending today.",
    changeAnytime:"You can change this anytime.", pushNotifications:"Push Notifications",
    cameraLabel:"Camera", uploadLabel:"Upload", removeLabel:"Remove",
    editLabel:"Edit", recordLabel:"Record", barLabel:"Bar", lineLabel:"Line",
    paidProgress:"Progress", cancelLabel:"Cancel", saveLabel:"Save",
    thisMonthLabel:"This month", lastMonthLabel:"Last month",

  }
};
